# [START runtime]
runtime: python27
threadsafe: yes
# [END runtime]

default_expiration: "7d"

handlers:
- url: /(.*\.json)
  mime_type: application/json
  static_files: dist/\1
  upload: dist/(.*\.json)
  secure: always

- url: /(.*\.mp4)
  mime_type: video/mp4
  static_files: dist/\1
  upload: dist/(.*\.mp4)
  secure: always

- url: /(.*\.(gif|png|jpg|css|js|otf|eot|svg|ttf|woff|woff2)(|\.map))$
  static_files: dist/\1
  upload: dist/(.*)(|\.map)
  secure: always

# Routing for typedoc, assets and favicon.ico to serve directly
- url: /((?:assets|docs)/.*|favicon\.ico)
  secure: always
  redirect_http_response_code: 301
  static_files: dist/\1
  upload: dist/.*



# index files
- url: (.*)/
  secure: always
  redirect_http_response_code: 301
  static_files: dist/\1/index.htm
  upload: dist

- url: (.*)
  secure: always
  redirect_http_response_code: 301
  static_files: dist\1
  upload: dist

# Any other requests are routed to index.html for angular to handle so we don't need hash URLs
#- url: /(.*)
#  secure: always
#  redirect_http_response_code: 301
#  static_files: dist/index.htm
#  upload: dist/index\.htm
#  http_headers:
#    Strict-Transport-Security: max-age=31536000; includeSubDomains
#    X-Frame-Options: DENY

  #redirect_http_response_code: 301

#- url: /(.*\.(gif|png|jpg|css|js|otf|eot|svg|ttf|woff|woff2)(|\.map))$
#  static_files: dist/\1
#  upload: dist/(.*)(|\.map)

#- url: /(.*)
#  static_files: dist/index.html
#  upload: dist/index.html

# Temporary setting to keep gcloud from uploading not required files for deployment
skip_files:
- ^node_modules$
- ^app\.yaml
- ^README\..*
- \.gitignore
- ^\.git$
- ^grunt\.js
- ^src$
- ^e2e$
- \.editorconfig
- ^karma\.config\.js
- ^package\.json
- ^protractor\.conf\.js
- ^tslint\.json